services:
  pgdb:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      start_period: 1m
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-init/pgdb-init.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  api:
    build:
      context: .
    env_file:
      - .env
    environment:
      AIS_API_KEY: ${AIS_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      pgdb:
        condition: service_healthy

volumes:
  pgdata:
